const BAD_REQUEST_STATUS_CODE = 400;
const REQUEST_NOT_FOUND = 404;
const CONFLICT_STATUS_CODE = 409;
const DEFAULT_ERROR = 500;
const UNAUTHORIZED_STATUS_CODE = 401;
const FORBIDDEN = 403;

module.exports = {
  BAD_REQUEST_STATUS_CODE,
  REQUEST_NOT_FOUND,
  DEFAULT_ERROR,
  CONFLICT_STATUS_CODE,
  UNAUTHORIZED_STATUS_CODE,
  FORBIDDEN,
};
